---
name: victim
namespace: victim
image: kieranajp/victim
version: latest
port: 3000

ingress:
  domain: example.com
  path: /victim

replicas: 1

# imagePullSecret: docker-registry-pullsecret

storage:
  class: local-path
  size: 1Gi

secrets:
- SLACK_CLIENT_ID
- SLACK_CLIENT_SECRET
