---
apiVersion: v1
kind: Endpoints
metadata:
  name: victim-db
subsets:
  - addresses:
      - ip: {{ .Values.database.host }}
    ports:
      - port: {{ .Values.database.port }}

---
apiVersion: v1
kind: Service
metadata:
  name: victim-db
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.database.port }}
      targetPort: {{ .Values.database.port }}
