---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:

      {{- if .Values.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret }}
      {{- end }}

      volumes:
      - name: victim-db-pvc
        persistentVolumeClaim:
          claimName: victim-db-pvc

      containers:
      - image: "{{ .Values.image }}:{{ .Values.version }}"
        name: {{ .Values.name }}
        imagePullPolicy: Always
        command: [ "/victim" ]
        ports:
        - containerPort: {{ .Values.port }}
          protocol: TCP
        volumeMounts:
        - name: victim-db-pvc
          mountPath: /data
        env:
        - name: LISTEN_ADDRESS
          value: "0.0.0.0:{{ .Values.port }}"
        {{- range .Values.secrets }}
        - name: {{ . }}
          valueFrom:
            secretKeyRef:
              name: "{{ include "chart.name" $ }}-secrets"
              key: {{ . }}
        {{- end }}
          
