apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: victim-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.class }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
