---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
  type: ClusterIP
  ports:
    - port: {{ .Values.port }}
      targetPort: api
      protocol: TCP
      name: api
